// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_IFJZRu2zT_gDpSAkFUTqKabCXsFL2HE',
    appId: '1:1094333785712:web:1c6250e7a4f223bae136b5',
    messagingSenderId: '1094333785712',
    projectId: 'wooshy-washy',
    authDomain: 'wooshy-washy.firebaseapp.com',
    databaseURL: 'https://wooshy-washy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wooshy-washy.appspot.com',
    measurementId: 'G-QNLXW80X7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfZMA7DPPY_kInOAD3_KN5leSb-TB4AYk',
    appId: '1:1094333785712:android:9b0e91716813d2ece136b5',
    messagingSenderId: '1094333785712',
    projectId: 'wooshy-washy',
    databaseURL: 'https://wooshy-washy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wooshy-washy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ5gneOUjegMQDkIQtjamSePtNIFuxmcg',
    appId: '1:1094333785712:ios:fa195711196d7385e136b5',
    messagingSenderId: '1094333785712',
    projectId: 'wooshy-washy',
    databaseURL: 'https://wooshy-washy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wooshy-washy.appspot.com',
    iosClientId: '1094333785712-99r6p329r61gkucv6ohsai962rihdvh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.wooshyWashy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ5gneOUjegMQDkIQtjamSePtNIFuxmcg',
    appId: '1:1094333785712:ios:e153e19d4f16ed18e136b5',
    messagingSenderId: '1094333785712',
    projectId: 'wooshy-washy',
    databaseURL: 'https://wooshy-washy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wooshy-washy.appspot.com',
    iosClientId: '1094333785712-2gnu9sdrroe87t7icjmbqifi1jdd7ns8.apps.googleusercontent.com',
    iosBundleId: 'com.example.wooshyWashy.RunnerTests',
  );
}
